### ISSUE TITLE
Mod does not work on servers (mixins)

### ISSUE THREAD

**Issue by JSJBDEV** [OpenlyFay/AncientGateways#5]
```
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot load class openlyfay.ancientgateways.mixins.ClientPlayNetworkHandlerMixin in environment type SERVER
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:855)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648)
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514)
        ... 27 more
Caused by: java.lang.RuntimeException: Cannot load class openlyfay.ancientgateways.mixins.ClientPlayNetworkHandlerMixin in environment type SERVER
        at net.fabricmc.loader.transformer.FabricTransformer.transform(FabricTransformer.java:75)
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:185)
        at net.fabricmc.loader.launch.knot.Knot.getClassByteArray(Knot.java:214)
        at net.fabricmc.loader.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:47)
        at net.fabricmc.loader.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:63)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1295)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:848)
        ... 30 more
```
This is running 1.16.5 fabric ancient-gateways-1.1.1

**Comment by OpenlyFay** [comment]
Fixed with 1.1.2, that mixin has been set to client-only
